FROM mirror.gcr.io/library/rust:1.97.1-slim-bookworm

# Test disabled network access
RUN if getent hosts www.google.com; then echo "Has network access!"; exit 1; fi

WORKDIR /src

ARG CARGO_BUILD_JOBS
RUN cargo install --frozen --path .

ENTRYPOINT ["rustic"]
