FROM mirror.gcr.io/golang:1.25-alpine as golang
FROM mirror.gcr.io/node:24-alpine as node

FROM node
COPY --from=golang /usr/local/go /usr/local/go

# Test disabled network access
RUN if getent hosts www.google.com; then echo "Has network access!"; exit 1; fi

# Link go to standard PATH location
RUN ln -s /usr/local/go/bin/go /usr/local/bin/go

WORKDIR /src/gomod-package
RUN . /tmp/hermeto.env && go build

WORKDIR /src/npm-package
RUN . /tmp/hermeto.env && npm install
