# SPDX-License-Identifier: GPL-3.0-only
"""Parser for uv.lock files.

uv.lock is a standard TOML file generated by the uv package manager.
This module parses it into structured Python objects for downstream processing.
"""
import logging
import sys

if sys.version_info >= (3, 11):
    import tomllib
else:
    import tomli as tomllib
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path

from hermeto.core.errors import InvalidLockfileFormat, LockfileNotFound

log = logging.getLogger(__name__)

# Only lockfile version 1 is currently supported
SUPPORTED_LOCKFILE_VERSION = 1


class SourceType(str, Enum):
    """Possible source types for a package in uv.lock."""

    REGISTRY = "registry"
    GIT = "git"
    URL = "url"
    DIRECTORY = "directory"
    EDITABLE = "editable"
    VIRTUAL = "virtual"


@dataclass(frozen=True)
class PackageSource:
    """Represents where a package comes from."""

    source_type: SourceType
    url: str | None = None  # registry URL, git URL, direct URL, or local path

    @classmethod
    def from_dict(cls, source_data: dict) -> "PackageSource":
        """Parse source from uv.lock inline table.

        Examples:
            { registry = "https://pypi.org/simple" }
            { git = "https://github.com/org/repo.git?tag=1.0#abc123" }
            { url = "https://files.pythonhosted.org/.../pkg.whl" }
            { directory = "../local-pkg" }
            { editable = "." }
            { virtual = "." }
        """
        for stype in SourceType:
            if stype.value in source_data:
                return cls(source_type=stype, url=source_data[stype.value])
        raise InvalidLockfileFormat(
            lockfile_path=Path("uv.lock"),
            err_details=f"Unknown source type in: {source_data}",
            solution="Check that the uv.lock file was generated by a supported version of uv.",
        )


@dataclass(frozen=True)
class Artifact:
    """A downloadable artifact (sdist or wheel) with URL and hash."""

    url: str
    hash: str  # format: "sha256:..."
    size: int = 0

    @classmethod
    def from_dict(cls, data: dict) -> "Artifact":
        return cls(
            url=data.get("url", ""),
            hash=data.get("hash", ""),
            size=data.get("size", 0),
        )


@dataclass(frozen=True)
class Dependency:
    """A dependency reference with optional PEP 508 marker."""

    name: str
    marker: str | None = None

    @classmethod
    def from_dict(cls, data: dict) -> "Dependency":
        return cls(
            name=data.get("name", ""),
            marker=data.get("marker"),
        )


@dataclass
class UvPackage:
    """Represents a single [[package]] entry in uv.lock."""

    name: str
    version: str
    source: PackageSource
    sdist: Artifact | None = None
    wheels: list[Artifact] = field(default_factory=list)
    dependencies: list[Dependency] = field(default_factory=list)
    dev_dependencies: dict[str, list[Dependency]] = field(default_factory=dict)

    @property
    def is_registry(self) -> bool:
        return self.source.source_type == SourceType.REGISTRY

    @property
    def is_git(self) -> bool:
        return self.source.source_type == SourceType.GIT

    @property
    def is_url(self) -> bool:
        return self.source.source_type == SourceType.URL

    @property
    def is_path(self) -> bool:
        return self.source.source_type == SourceType.DIRECTORY

    @property
    def is_editable(self) -> bool:
        return self.source.source_type in (SourceType.EDITABLE, SourceType.VIRTUAL)


@dataclass
class UvLockfile:
    """Parsed representation of a uv.lock file."""

    version: int
    requires_python: str
    packages: list[UvPackage]
    manifest_members: list[str] | None = None  # workspace members if present

    @property
    def is_workspace(self) -> bool:
        return self.manifest_members is not None

    def get_package(self, name: str) -> UvPackage | None:
        """Find a package by name."""
        for pkg in self.packages:
            if pkg.name == name:
                return pkg
        return None


def _parse_package(data: dict) -> UvPackage:
    """Parse a single [[package]] entry from uv.lock."""
    source_data = data.get("source", {})
    source = PackageSource.from_dict(source_data)

    # Parse sdist
    sdist = None
    if "sdist" in data:
        sdist = Artifact.from_dict(data["sdist"])

    # Parse wheels
    wheels = [Artifact.from_dict(w) for w in data.get("wheels", [])]

    # Parse dependencies
    dependencies = [Dependency.from_dict(d) for d in data.get("dependencies", [])]

    # Parse dev dependencies (only present on project's own package)
    dev_deps: dict[str, list[Dependency]] = {}
    if "dev-dependencies" in data:
        for group, deps in data["dev-dependencies"].items():
            dev_deps[group] = [Dependency.from_dict(d) for d in deps]

    return UvPackage(
        name=data.get("name", ""),
        version=data.get("version", ""),
        source=source,
        sdist=sdist,
        wheels=wheels,
        dependencies=dependencies,
        dev_dependencies=dev_deps,
    )


def parse_uv_lockfile(lockfile_path: Path) -> UvLockfile:
    """Parse a uv.lock file into a structured UvLockfile object.

    :param lockfile_path: absolute path to the uv.lock file
    :return: parsed UvLockfile
    :raises LockfileNotFound: if the file does not exist
    :raises InvalidLockfileFormat: if the file is not valid TOML or has unsupported version
    """
    if not lockfile_path.exists():
        raise LockfileNotFound(files=lockfile_path)

    try:
        with open(lockfile_path, "rb") as f:
            data = tomllib.load(f)
    except tomllib.TOMLDecodeError as e:
        raise InvalidLockfileFormat(
            lockfile_path=lockfile_path,
            err_details=str(e),
            solution="Ensure the uv.lock file is valid TOML. Try regenerating with 'uv lock'.",
        )

    # Validate version
    version = data.get("version")
    if version != SUPPORTED_LOCKFILE_VERSION:
        raise InvalidLockfileFormat(
            lockfile_path=lockfile_path,
            err_details=f"Unsupported lockfile version: {version} (expected {SUPPORTED_LOCKFILE_VERSION})",
            solution="Update hermeto or check your uv version compatibility.",
        )

    requires_python = data.get("requires-python", "")

    # Parse all packages
    packages = [_parse_package(pkg) for pkg in data.get("package", [])]

    # Check for workspace manifest
    manifest_members = None
    if "manifest" in data:
        manifest_members = data["manifest"].get("members", [])

    log.info(
        "Parsed uv.lock: %d packages, version=%d, workspace=%s",
        len(packages),
        version,
        manifest_members is not None,
    )

    return UvLockfile(
        version=version,
        requires_python=requires_python,
        packages=packages,
        manifest_members=manifest_members,
    )
