FROM localhost/hermeto:latest

ENTRYPOINT []

RUN cp -r /tmp/hermeto-output/deps/huggingface/ /deps

ENV HF_HUB_CACHE=/deps/hub
ENV HF_HUB_OFFLINE=1

CMD ["/venv/bin/python3", "-c", "from huggingface_hub import snapshot_download; path = snapshot_download('hf-internal-testing/tiny-random-gpt2', local_files_only=True); print(path)"]
