# A corresponding rpms.lock.yaml was built for UBI9
FROM registry.access.redhat.com/ubi9/ubi@sha256:d342aa80781bf41c4c73485c41d8f1e2dbc40ee491633d9cafe787c361dd44ff as ubi

# Test disabled network access
RUN if curl -IsS www.google.com; then echo "Has network access!"; exit 1; fi

# These packages must be prefetched during the previous phase.
# Refer to the test for further details.
RUN dnf -y install \
    cargo \
    python3 \
    python3-pip \
    python3-setuptools \
    python3-wheel \
    python3-devel \
    libffi-devel \
    openssl-devel

WORKDIR /src

RUN . /tmp/cachi2.env \
    # This creates a cargo config on the same level as cachi2-output
    && mkdir /tmp/.cargo \
    && echo "[source.crates-io]" > /tmp/.cargo/config.toml \
    && echo 'replace-with = "local"' >> /tmp/.cargo/config.toml \
    && echo "[source.local]" >> /tmp/.cargo/config.toml \
    && echo 'directory = "/tmp/cachi2-output/deps/cargo"' >> /tmp/.cargo/config.toml \
    && python3 -m pip install -r requirements.txt

# See pip/e2e for the resasoning behind switching WORKDIR
RUN cp -r /src /app
WORKDIR /app
