name: Publish Container Image

on:
  release:
    types: [published]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    name: Build and push container image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-tags: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # NOTE: the resulting image is tagged as follows:
      # 1. [ALWAYS] Semantic version tag:
      #    - extracts version from github.ref (must be a git tag ref)
      #
      # 2. [CONDITIONAL] 'latest' tag to ensure latest points to stable releases only:
      #    - release event: only for stable releases, i.e. '!github.event.release.prerelease'
      #    - manual workflow trigger: only if 'push_latest' checkbox is checked
      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest,enable=${{ !github.event.release.prerelease }}

      # Multi-arch build setup
      - name: Build and push container image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
